sudo: false
language: ruby
rvm:
  - 2.4.2
before_install: gem install bundler -v 1.15.4

env:
  CODECLIMATE_REPO_TOKEN: some-key

services:
  - mongodb

script:
  - bundle install
  - bundle exec rspec